### ISSUE TITLE
 Bug in ClutterR_Part1_rawdata.m: Undefined function “displacement_model_sin_TS

### ISSUE THREAD

**Issue by Zhenyu98** [Benyaminhosseiny/ClutterFree-GBInSAR#1]
## Description
As instructed by the README.md, we tried running the  `ClutterR_Part1_rawdata.m`  first. However, upon execution, MATLAB throws an error indicating that the function displacement_model_sin_TS is undefined. This issue occurs at line 111, where the function is called.

## Steps to Reproduce
1. Run the `ClutterR_Part1_rawdata.m` script in MATLAB.
2. Error is thrown at line 111 with the following message: `Undefined function 'displacement_model_sin_TS' 

## Expected Behavior
The script should run without errors, and the function `displacement_model_sin_TS` should compute the displacement as intended.

## Actual Behavior
The script stops execution due to the undefined function error, and no output is generated.

## Possible Fix
It seems that the function displacement_model_sin_TS might be missing from the repository. If this function is a custom utility that's expected to be part of the codebase, it may not have been included in the list of files. Could you please check if this function is part of a separate file that needs to be uploaded? It would be greatly appreciated if you could provide this function or guide on how to implement it if it is not meant to be included.

## Operating Environment
- MATLAB version: [MATLAB R2023a]
- Operating System: [Window 10]

## Screenshots
![1708604595159](https://github.com/Benyaminhosseiny/ClutterFree-GBInSAR/assets/62387006/d8e8781d-93fd-4651-9b5d-ccd726fe35ee)

## Additional Context
Firstly, I appreciate your constructive contributions to GB-SAR and the publication of high-quality papers. Your work not only inspires but also serves as a valuable reference.

Furthermore, I am deeply grateful for your willingness to share your code on the GitHub platform，this would contribute to result reproducibility and serve as a valuable resource for our community.  

Thank you once again for your outstanding work. I look forward with interest to any future updates you may choose to share, particularly regarding the code for your published high-quality papers. Your current and potential contributions are highly valued within our community.

**Comment by Benyaminhosseiny** [comment]
Hi @Zhenyu98 
Thank you for raising this issue.
You are right. I forgot to add this function. 
Please check the codes again and if it is fixed please close the issue.
Thanks again
Benyamin

**Comment by Zhenyu98** [comment]
> Hi @Zhenyu98 Thank you for raising this issue. You are right. I forgot to add this function. Please check the codes again and if it is fixed please close the issue. Thanks again Benyamin

Hi Benyamin,

Thank you for the prompt response and for adding the missing `displacement_model_sin_TS` function to the repository. I have pulled the latest changes and can confirm that the previous issue has been resolved successfully.

However, I have encountered a similar problem with another function named `signal_model_TS`. It appears that this function is also not defined within the current repository files. The error occurs when attempting to run the `Continuous_dsplcmnt_Part1_rawdata.m` script, as highlighted in the attached screenshot.

Would it be possible for you to also include the `signal_model_TS` function? Having this function would be immensely helpful for anyone looking to fully utilize the GB-SAR processing scripts you've provided.

Thank you once again for your support and contributions to the community.

Thanks again，
Zhenyu

![image](https://github.com/Benyaminhosseiny/ClutterFree-GBInSAR/assets/62387006/a2eabf3b-f3c3-425b-bb9a-65585322d75a)

**Comment by Benyaminhosseiny** [comment]
Hello Zhenyu
Thank you again for reviewing the code. I think there was an issue with my local machine. I added the missing function. Please check the codes again and if there is an issue please kindly let me know.
Thanks
Benyamin

**Comment by Zhenyu98** [comment]
Hi Benyamin,

Thank you for the quick update and for adding the `signal_model_TS` function. I've updated my local copy of the code and the previous issue with `signal_model_TS` is now resolved.

However, I've run into a similar issue with another function called `create_slc`. This function is called in the `Continuous_dsplcmnt_Part2_processing.m` script, but it appears to be undefined or not included in the repository. The error occurs at line 41 where `create_slc` is called. 

Thank you once again for your attention to these matters and for your support of the community.
Zhenyu

**Comment by Benyaminhosseiny** [comment]
Hello again,
Thank you for patiently reviewing the codes and sorry for the bugs. I added the missing function. I hope this is the last one and the codes work :)
 
Thanks
Benyamin

**Comment by Zhenyu98** [comment]
Hi Benyamin,

I just pulled the latest released codes and everything is working smoothly now. Thank you very much for addressing the issues so promptly and for your patience throughout the process. 

Warm regards,
Zhenyu

**Comment by Benyaminhosseiny** [comment]
Hi Zhenyu
Great to hear!
Thank you for your help in debugging the codes.

All the best
Benyamin
